### ISSUE TITLE
redundancy?

### ISSUE THREAD

**Issue by petaflot** [casey/dotify#1]
surprised I didn't find your repos before.

was I blind?

are you?

see https://github.com/petaflot/bytes_as_braille

One issue I see is that we need to come to a consensus on how to do the mapping. Since I reordered the cells (in case you did not), I suggest we use my POV

**Comment by casey** [comment]
I don't think I reorder them, and I agree that it's much nicer if you. This repo is pretty old and dusty, and I don't even know if anyone uses it, so I'll probably just leave it the way it is.

**Comment by petaflot** [comment]
would you mind putting a link to my repo in your description?


the idea is really to avoid having different standards/paradigms (aka  
substandards, dialects or whatever you could call it) from interfering  
with each other ; there is enough misunderstanding and wars in this  
Universe).


Cheers


ps: part of me is a little upset you came up with that idea before I did XD


Casey Rodarmor ***@***.***> a écrit :

> I don't think I reorder them, and I agree that it's much nicer if  
> you. This repo is pretty old and dusty, and I don't even know if  
> anyone uses it, so I'll probably just leave it the way it is.
>
> --
> Reply to this email directly or view it on GitHub:
> https://github.com/casey/dotify/issues/1#issuecomment-1788121904
> You are receiving this because you authored the thread.
>
> Message ID: ***@***.***>


-- 
The e-mail address used as "sender" is a temporary e-mail address. If  
you feel you need to keep contact with me for more than a few weeks or  
months, please request a permanent, personal e-mail address to which  
to send your messages.

This email and any attachments to it may be confidential and are  
intended solely for the use of the individual to whom it is addressed  
(indicated by the account details in the subject line). Please notify  
the sender immediately by e-mail if you have received this e-mail by  
mistake and immediately delete this e-mail from your system. E-mail  
transmission cannot be guaranteed to be secure or error-free as  
information could be intercepted, corrupted, lost, destroyed, arrive  
late or incomplete, or contain viruses. The sender therefore does not  
accept liability for any errors or omissions in the contents of this  
message, which arise as a result of e-mail transmission.
